on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'README.md'

jobs:
  render_site:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Render
        uses: quarto-dev/quarto-actions/render@v2
        with:
          to: html
